// Generated by https://quicktype.io

export interface Employee {
    id:          number;
    ci:          number;
    created_at:  string;
    nombre:      string;
    apellidos:   string;
    descripcion: string;
    password:    string;
    rol:         number;
}
